apiVersion: apps/v1
kind: Deployment
metadata:
  name: aktieanalys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aktieanalys
  template:
    metadata:
      labels:
        app: aktieanalys
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.43.0.10
        searches:
          - aktieanalys.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "2"
      containers:
      - name: aktieanalys
        image: localhost/aktieanalys:v24.6-1788979883
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
        env:
        - name: REQUESTS_CA_BUNDLE
          value: /etc/ssl/certs/ca-certificates.crt
        - name: SSL_CERT_FILE
          value: /etc/ssl/certs/ca-certificates.crt
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api
              key: GEMINI_API_KEY
        volumeMounts:
        - name: data
          mountPath: /app/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: aktieanalys-data
---
apiVersion: v1
kind: Service
metadata:
  name: aktieanalys
spec:
  selector:
    app: aktieanalys
  ports:
  - port: 80
    targetPort: 4000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aktieanalys
spec:
  rules:
  - host: aktieanalys.192.168.1.176.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aktieanalys
            port:
              number: 80
  - host: aktieanalys.192.168.2.163.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aktieanalys
            port:
              number: 80

