apiVersion: v1 
kind: PersistentVolumeClaim                                                                                       
metadata:                                                                                                         
  name: aktieanalys-data
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi

